"""add chat_moderations table

Revision ID: 29e2955419aa
Revises: f0c25a843752
Create Date: 2026-08-18 12:32:05.732357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e2955419aa'
down_revision = 'f0c25a843752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_moderations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.Column('last_violation_at', sa.DateTime(), nullable=True),
    sa.Column('last_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_moderations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_moderations_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_moderations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_moderations_user_id'))

    op.drop_table('chat_moderations')
    # ### end Alembic commands ###
