"""add last_seen_chat_at to player_stats

Revision ID: 4890ace02582
Revises: dd90332828d6
Create Date: 2026-08-17 22:35:30.961000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4890ace02582'
down_revision = 'dd90332828d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_chat_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_column('last_seen_chat_at')

    # ### end Alembic commands ###
