"""add chat_reports table

Revision ID: 65eb96e43ee2
Revises: 4890ace02582
Create Date: 2026-08-17 23:15:09.069291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65eb96e43ee2'
down_revision = '4890ace02582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=False),
    sa.Column('content_snapshot', sa.String(length=500), nullable=False),
    sa.Column('is_violation', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'reporter_id', name='uq_chat_report_message_reporter')
    )
    with op.batch_alter_table('chat_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_reports_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_reports_reported_user_id'), ['reported_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_reports_reporter_id'), ['reporter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_chat_reports_reported_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_reports_message_id'))

    op.drop_table('chat_reports')
    # ### end Alembic commands ###
