"""Add gold to player_stats

Revision ID: 6e4a3405a716
Revises: fb5c6ec0373c
Create Date: 2026-08-14 01:07:58.020455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4a3405a716'
down_revision = 'fb5c6ec0373c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_column('gold')

    # ### end Alembic commands ###
