"""add missed_facts table for per-fact spaced repetition

Revision ID: 7ad0e7899b9c
Revises: 7a3f9c1d2b44
Create Date: 2026-08-21 04:28:30.305562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad0e7899b9c'
down_revision = '7a3f9c1d2b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missed_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('miss_count', sa.Integer(), nullable=False),
    sa.Column('correct_streak', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', 'fingerprint', name='uq_missed_fact')
    )
    with op.batch_alter_table('missed_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missed_facts_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_missed_facts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missed_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missed_facts_user_id'))
        batch_op.drop_index(batch_op.f('ix_missed_facts_topic_id'))

    op.drop_table('missed_facts')
    # ### end Alembic commands ###
