"""add icon_key to subjects

Revision ID: 90e8a5f78a12
Revises: dd07ce50eac3
Create Date: 2026-08-12 00:50:31.684891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e8a5f78a12'
down_revision = 'dd07ce50eac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_key', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('icon_key')

    # ### end Alembic commands ###
