"""Add item_instances table

Revision ID: c605d2bc5d05
Revises: dc7ffc0b2626
Create Date: 2026-08-13 20:11:40.930354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c605d2bc5d05'
down_revision = 'dc7ffc0b2626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon_key', sa.String(length=40), nullable=False),
    sa.Column('passive_type', sa.String(length=20), nullable=False),
    sa.Column('passive_value', sa.Float(), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_instances_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_instances_user_id'))

    op.drop_table('item_instances')
    # ### end Alembic commands ###
