"""Add marketplace: item listings and shop offers

Revision ID: d026d810bdfb
Revises: 6e4a3405a716
Create Date: 2026-08-14 01:50:03.556043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd026d810bdfb'
down_revision = '6e4a3405a716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon_key', sa.String(length=40), nullable=False),
    sa.Column('passive_type', sa.String(length=20), nullable=False),
    sa.Column('passive_value', sa.Float(), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_listed', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('list_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('listed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_instances', schema=None) as batch_op:
        batch_op.drop_column('listed_at')
        batch_op.drop_column('list_price')
        batch_op.drop_column('is_listed')

    op.drop_table('shop_offers')
    # ### end Alembic commands ###
