"""add duels table

Revision ID: f0c25a843752
Revises: 65eb96e43ee2
Create Date: 2026-08-18 00:08:47.482035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c25a843752'
down_revision = '65eb96e43ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=24), nullable=False),
    sa.Column('challenger_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('challenger_hp', sa.Integer(), nullable=False),
    sa.Column('opponent_hp', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('current_prompt', sa.String(length=200), nullable=True),
    sa.Column('current_answer', sa.String(length=200), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duels_challenger_id'), ['challenger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duels_opponent_id'), ['opponent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duels_room_code'), ['room_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duels_room_code'))
        batch_op.drop_index(batch_op.f('ix_duels_opponent_id'))
        batch_op.drop_index(batch_op.f('ix_duels_challenger_id'))

    op.drop_table('duels')
    # ### end Alembic commands ###
