"""Add character class to profiles

Revision ID: fb5c6ec0373c
Revises: c605d2bc5d05
Create Date: 2026-08-13 21:16:34.084169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5c6ec0373c'
down_revision = 'c605d2bc5d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_class', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('class_tier_claimed', sa.Integer(), nullable=False, server_default='-1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('class_tier_claimed')
        batch_op.drop_column('character_class')

    # ### end Alembic commands ###
